### ISSUE TITLE
Подсчет числа символов при твите

### ISSUE THREAD

**Issue by Ruszrok** [rozboris/Sublime-Tweet#1]
Когда постишь длинный твит через sublime tweet, то хотелось бы чтобы считались символы.

**Comment by rozboris** [comment]
Уже добавил вчера ночью в https://github.com/rozboris/Sublime-Tweet/commit/3deef14e3fad5100e2a88685923525ccc555dcb3

**Comment by Ruszrok** [comment]
,          issue)))

22  2011 . 14:38  Boris Rozenshteyn <
reply@reply.github.com>:

> https://github.com/rozboris/Sublime-Tweet/commit/3deef14e3fad5100e2a88685923525ccc555dcb3
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rozboris/Sublime-Tweet/issues/1#issuecomment-2489425

##
