### ISSUE TITLE
"We have some connection issues" error

### ISSUE THREAD

**Issue by CieNTi** [rozboris/Sublime-Tweet#11]
Hi!

I just installed "Sublime Tweet" and tried. Authorized plugin on twitter and entered the PIN, but when I'm going to tweet or see timeline always get that error.

I'm not behind a proxy or something similar, my connection it's just normal

What i'm doing wrong?

Thanks !

**Comment by JAForbes** [comment]
I am having the same problem.

**Comment by rozboris** [comment]
Will be fixed as a part of ST3 porting #13
