### ISSUE TITLE
Port to Sublime Text3

### ISSUE THREAD

**Issue by lmedinas** [rozboris/Sublime-Tweet#13]
This would be a wonderful change to support ST3 and the latest Twitter API.

**Comment by rozboris** [comment]
Is there anyone who can take care of the project? I have zero time and zero interest in it now, so I'm very sorry for all the users suffering from the bugs :/

**Comment by rozboris** [comment]
Ok, it looks like I have enough time and after waiting for 2 years I'm almost complete with porting. Hold on everyone, the update it coming in a few days!

**Comment by rozboris** [comment]
Ported and closed. Please update from Package Control!
