### ISSUE TITLE
ImportError: No module named get_access_token

### ISSUE THREAD

**Issue by dotzero** [rozboris/Sublime-Tweet#2]
При любом действии вываливается в консоль

```
Traceback (most recent call last):
  File "./SublimeTweet.py", line 167, in runIfInternetIsUp
  File "./SublimeTweet.py", line 253, in register
ImportError: No module named get_access_token
```

Система MacOS

**Comment by rozboris** [comment]
А вы положили папку libs рядом с SublimeTweet.py? Похоже, что вы выкачали не весь дистрибутив.

**Comment by dotzero** [comment]
Только перенос 

```
from libs.get_access_token import TwitterAccessTokenRequester
```

в начало файла помог.

**Comment by dotzero** [comment]
Я делал git clone зачем руками что-то копировать.

**Comment by rozboris** [comment]
Спасибо за фикс, строчка куда-то потерялась в последних коммитах. Скоро пофикшу.
