### ISSUE TITLE
Getting this error after installing.

### ISSUE THREAD

**Issue by nwjlyons** [rozboris/Sublime-Tweet#3]
Traceback (most recent call last):
  File "./sublime_plugin.py", line 57, in reload_plugin
  File "./SublimeTweet.py", line 5, in <module>
    import libs.twitter
  File "./libs/twitter.py", line 66, in <module>
    import oauth2 as oauth
  File "./libs/oauth2.py", line 31, in <module>
    import httplib2
  File "./libs/httplib2.py", line 795, in <module>
    class HTTPSConnectionWithTimeout(httplib.HTTPSConnection):
AttributeError: 'module' object has no attribute 'HTTPSConnection'

I'm running Ubuntu 10.10.

**Comment by rozboris** [comment]
Sorry for delayed answer.
I've noticed this bug, but I believe it happens only if you have cloned git repo when Sublime was open.
Is reopening of Sublime helps?
Please, reply, I'll try to fix it.

**Comment by jerel** [comment]
I'm also getting this error. I installed via Package Control and I've closed and reopened Sublime several times with no results. It never has asked for auth so the Tools > Tweet menu items are unclickable

Running Ubuntu 10.04 if that makes a difference

**Comment by arcv** [comment]
The problem is "Note: HTTPS support is only available if the socket module was compiled with SSL support." and Sublime Text 2 is using Python 2.6.

**Comment by ianleckey** [comment]
Same problem, any resolution to this?

**Comment by dalys** [comment]
I too am getting the exact same problem. I'm running Arch Linux and installed Sublime Tweet via Package Control.

**Comment by rozboris** [comment]
Please update through Package Control, it should work now.
